---
version: "3.7"

# This Docker composition file is used to build and test the container

services:
  steelix-server:
    # Run the container normally
    build:
      context: .
      dockerfile: src/apache2/Dockerfile
    container_name: steelixWeb
    init: true
    restart: "no"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/apache2/config/apache2.conf:/etc/apache2/apache2.conf
      - ./src/apache2/config/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./src/apache2/html:/var/www/html/
      - ./src/secrets/cert.pem:/etc/ssl/certs/cert.pem
      - ./src/secrets/privkey.pem:/etc/ssl/private/privkey.pem
      - ./src/secrets/chain.pem:/etc/ssl/private/chain.pem
