---
version: "3.7"

# This Docker composition file is used to build and test the container

services:
  steelix-server:
    # Run the container normally
    build:
      context: .
      dockerfile: src/apache2/Dockerfile
    container_name: steelixWeb
    init: true
    restart: "no"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/apache2/config/apache2.conf:/etc/apache2/apache2.conf
      - ./src/apache2/config/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./src/secrets/default.cert:/etc/ssl/certs/default.cert
      - ./src/secrets/default.key:/etc/ssl/private/default.key
      - ./src/secrets/ca_bundle.crt:/etc/ssl/private/ca_bundle.crt
